// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateNote(arg1:string,arg2:string,arg3:string,arg4:any):Promise<models.Note>;

export function CreateWorkspace(arg1:string):Promise<models.Workspace>;

export function DeleteNote(arg1:string):Promise<void>;

export function GetNote(arg1:string):Promise<models.Note>;

export function GetWorkspace(arg1:string):Promise<models.Workspace>;

export function Greet(arg1:string):Promise<string>;

export function ListNotes(arg1:string):Promise<Array<models.Note>>;

export function ListWorkspaces():Promise<Array<models.Workspace>>;

export function ToggleFavorite(arg1:string):Promise<void>;

export function UpdateNote(arg1:string,arg2:string,arg3:string):Promise<void>;
