// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthenticateDrive(arg1) {
  return window['go']['main']['App']['AuthenticateDrive'](arg1);
}

export function CreateNote(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateNote'](arg1, arg2, arg3, arg4);
}

export function CreateWorkspace(arg1) {
  return window['go']['main']['App']['CreateWorkspace'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function GetDriveAuthURL() {
  return window['go']['main']['App']['GetDriveAuthURL']();
}

export function GetNote(arg1) {
  return window['go']['main']['App']['GetNote'](arg1);
}

export function GetSyncStatus() {
  return window['go']['main']['App']['GetSyncStatus']();
}

export function GetWorkspace(arg1) {
  return window['go']['main']['App']['GetWorkspace'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsDriveAuthenticated() {
  return window['go']['main']['App']['IsDriveAuthenticated']();
}

export function ListNotes(arg1) {
  return window['go']['main']['App']['ListNotes'](arg1);
}

export function ListWorkspaces() {
  return window['go']['main']['App']['ListWorkspaces']();
}

export function ToggleFavorite(arg1) {
  return window['go']['main']['App']['ToggleFavorite'](arg1);
}

export function TriggerSync() {
  return window['go']['main']['App']['TriggerSync']();
}

export function UpdateNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateNote'](arg1, arg2, arg3);
}
