// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AuthenticateDrive(arg1:string):Promise<void>;

export function CreateNote(arg1:string,arg2:string,arg3:string,arg4:any):Promise<models.Note>;

export function CreateWorkspace(arg1:string):Promise<models.Workspace>;

export function DeleteNote(arg1:string):Promise<void>;

export function GetDriveAccountInfo():Promise<Record<string, any>>;

export function GetDriveAuthURL():Promise<string>;

export function GetNote(arg1:string):Promise<models.Note>;

export function GetSyncStatus():Promise<Record<string, any>>;

export function GetWorkspace(arg1:string):Promise<models.Workspace>;

export function Greet(arg1:string):Promise<string>;

export function IsDriveAuthenticated():Promise<boolean>;

export function ListNotes(arg1:string):Promise<Array<models.Note>>;

export function ListWorkspaces():Promise<Array<models.Workspace>>;

export function SignOutDrive():Promise<void>;

export function StartDriveAuth():Promise<string>;

export function ToggleFavorite(arg1:string):Promise<void>;

export function TriggerSync():Promise<void>;

export function UpdateNote(arg1:string,arg2:string,arg3:string):Promise<void>;
